### PR TITLE
add cyrillic word support on word parser

### PR DESCRIPTION
**Pull request by tengis**
i would like to use this on cyrillic text but it doesn’t parse cyrillic words. 

So i implemented & added couple of test as well 

Also mentioned [here](https://github.com/lukeapage/node-markdown-spellcheck/pull/66#issuecomment-221540392) as well after upgraded inquirer to 1.0.0 cli interactive options quits just after first action. So updated prompt function on cli-interactive.js & updated tests as well

Thanks

### CODE REVIEW

**Comment by lukeapage** [comment]
thanks, sorry for the delay..

**Comment by lukeapage** [comment]
sorry will publish soon (next couple of days), ran out of time

**Comment by lukeapage** [comment]
published. sorry for the delay.

**Comment by tengis** [comment]
@lukeapage Great. Thanks

**Pull request merged**
