### PR TITLE
Update dependency containing moderate security flaw

### PR DESCRIPTION
**Pull request by dialex**
reported at https://www.npmjs.com/advisories/812

### CODE REVIEW

**Comment by robatwilliams** [comment]
Follows discussion started on this issue starting at https://github.com/lukeapage/node-markdown-spellcheck/issues/122#issuecomment-533238253

**Comment by dialex** [comment]
> We specify ^0.3.5, anyone installing it will get 0.7.0 so I'm not sure this is much of a concern for this project. Correct me if I'm wrong. So I don't see reason to do a release right now. Thanks for the PR.

Not really, with `^0.3.5` you will get all patch updates -- in this specific case you will get up to `0.3.19`. The security flaw was only patched at `0.6.3`. In the meantime, we are at risk.

Screenshot 2019-09-19 at 19 11 50

**Comment by robatwilliams** [comment]
Continuing from the discussion on the unrelated issue...

Sorry 🤦‍♂ ... I didn't remember that the caret works differently below version 1.

I'll try and get round to checking this against some real content and doing a release.

**Comment by robatwilliams** [comment]
Works fine on our content. AppVeyor problem is something with latest Node 12; ignoring.

**Comment by robatwilliams** [comment]
Wait until https://github.com/markedjs/marked/issues/1456 fix is released (it was merged yesterday) before doing a release.

There have been many [breaking changes](https://github.com/markedjs/marked/releases) (although they are fixes) to `marked` since the 0.3.5 version that was originally installed in this project. They look safe enough, but it's over 4 years' worth of changes, and I don't have time to deal with any issues they may cause for consumers of this library. I would rather keep the latest version stable, so I'm not doing a release.

Anyone who uses this library to process content that's outside their own control and is concerned about the vulnerability, should be able to use `npm audit fix` as described [here](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities) to force-upgrade the transitive dependency (ignore the likely semver warning).

**Comment by dialex** [comment]
@robatwilliams Reminder: It's been 6 months. Is there any update on this?

**Comment by dialex** [comment]
@robatwilliams I see this has been merged to master, yet no release was made in the last 6 months. The latest release (`1.3.1`) on NPM has 2 years!

Can you please push the latest master to npm, so we can update our packages and solve the vulnerability once and for all?

**Comment by robatwilliams** [comment]
I'm afraid I don't use this anymore. See my previous comment regarding 4 years' worth of `marked` changes.

**Comment by dialex** [comment]
I see. Still, you could simply release a major version `2.0.0`, and highlight it as version with breaking changes:

- Whoever wants to stay behind, fine, they can use `1.3.1`.
- If people like me and others need to fix security vulnerabilities, we'll take the risk and use `2.0.0`.

At least that way we have a choice. What do you think?

**Comment by robatwilliams** [comment]
I can publish 2.0.0-beta.0 if @lukeapage can give me publishing rights please.

**Pull request merged**
